name: "Podcast Generator"
author: "Salman Farsi"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  color: "red"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.action }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}